--USER 데이터 생성
INSERT INTO MEMBER (MEMBER_ID,  MEMBER_NAME) VALUES (1, 'jung');
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME) VALUES (2, 'hong');
INSERT INTO MEMBER (MEMBER_ID, MEMBER_NAME) VALUES (3, 'kim');

--PRODUCT 데이터 생성
INSERT INTO PRODUCT (PRODUCT_NAME, TARGET_FUNDING_PRICE, START_DATE, FINISH_DATE, FUNDING_STATUS, FUNDING_MEMBER_ID, TOTAL_FUNDING_PRICE, FUNDING_MEMBER_NUMBER)
VALUES ('환절기 토탈케어 펀딩', 500000, '2022-03-17 00:00:00', '2022-05-28 23:59:59', '펀딩중', 1, 250000, 0);
