CREATE TABLE PRODUCT (
                         PRODUCT_ID bigint generated by default as identity,
                         PRODUCT_NAME varchar(255),
                         TARGET_FUNDING_PRICE integer,
                         TOTAL_FUNDING_PRICE integer,
                         FUNDING_STATUS varchar(30),
                         FUNDING_MEMBER_ID bigint,
                         START_DATE timestamp,
                         FINISH_DATE timestamp,
                         FUNDING_MEMBER_NUMBER integer,
                         primary key (PRODUCT_ID)
);

CREATE TABLE FUNDING (
                         FUNDING_ID bigint generated by default as identity,
                         PRODUCT_ID bigint not null,
                         FUNDING_PRICE integer,
                         MEMBER_ID bigint not null,
                         FUNDING_DATE timestamp,
                         primary key(FUNDING_ID),
);